// PrivacyPage — Privacy Policy content, rendered inside the shared LegalPage chrome.
function PrivacyPage() {
  const href = window.NV_HREF || (() => "#");
  return (
    <window.LegalPage title="Privacy Policy" effective="Effective date: April 10, 2026">
      <h2>1. Introduction</h2>
      <p>Node Ventures Inc. ("Node Ventures", "we", "us", "our") is committed to protecting the privacy of individuals who interact with the Node Ventures Portal (the "Portal"). This Privacy Policy explains how we collect, use, disclose, and safeguard your personal information in accordance with Canada's <em>Personal Information Protection and Electronic Documents Act</em> (PIPEDA) and applicable provincial privacy legislation.</p>
      <p>By using the Portal, you consent to the practices described in this policy.</p>

      <h2>2. Information We Collect</h2>
      <p>We collect personal information that you voluntarily provide, including:</p>
      <ul>
        <li><strong>Account information:</strong> name, email address, and authentication credentials.</li>
        <li><strong>Consultant profile data:</strong> professional title, bio, LinkedIn URL, expertise tags, availability, hourly rate, profile photo, and CV/résumé.</li>
        <li><strong>Usage data:</strong> pages visited, actions taken within the Portal, and browser/device information collected through standard server logs.</li>
        <li><strong>Communications:</strong> messages you send to us or through the Portal.</li>
      </ul>
      <p>We do not knowingly collect personal information from individuals under 18 years of age.</p>

      <h2>3. How We Use Your Information</h2>
      <p>We use personal information to:</p>
      <ul>
        <li>Create and manage your account.</li>
        <li>Process consultant verification applications and facilitate matching.</li>
        <li>Track consultant contributions and calculate credits (Phase 2 onwards).</li>
        <li>Provide investor portfolio visibility to authorised investors.</li>
        <li>Send transactional emails (verification status updates, interview booking confirmations, and similar operational notices).</li>
        <li>Improve Portal functionality and user experience.</li>
        <li>Meet legal and regulatory obligations.</li>
      </ul>
      <p>We do not sell, rent, or trade your personal information to third parties for marketing purposes.</p>

      <h2>4. Third-Party Services</h2>
      <p>The Portal uses the following third-party services, each of which has its own privacy policy:</p>
      <ul>
        <li><strong>Google Firebase Authentication</strong> for account creation and sign-in. See <a href="https://firebase.google.com/support/privacy" target="_blank" rel="noopener">Firebase Privacy</a>.</li>
        <li><strong>Google Cloud Storage</strong> for secure storage of uploaded documents (profile photos, CVs, and deal-room files). Data is stored in Canada where available.</li>
        <li><strong>Google Cloud SQL</strong> for structured data storage.</li>
        <li><strong>Resend</strong> for transactional email delivery. See <a href="https://resend.com/privacy" target="_blank" rel="noopener">Resend Privacy</a>.</li>
      </ul>
      <p>We enter into data processing agreements with these providers as required and take reasonable steps to ensure they maintain appropriate safeguards.</p>

      <h2>5. Data Storage and Security</h2>
      <p>Your data is stored on servers located in Google Cloud infrastructure, with a preferred region of Canada (northamerica-northeast2). We implement industry-standard security measures including:</p>
      <ul>
        <li>Encrypted data in transit (TLS) and at rest.</li>
        <li>Role-based access controls limiting who can access personal data.</li>
        <li>Short-lived signed URLs for document access (documents are not publicly accessible).</li>
        <li>Audit logs for sensitive actions.</li>
      </ul>
      <p>No method of electronic storage or transmission is 100% secure. We cannot guarantee absolute security, but we are committed to using commercially reasonable measures to protect your information.</p>

      <h2>6. Document Uploads</h2>
      <p>Documents you upload (profile photos, CVs, and future deal-room files) are stored in Google Cloud Storage under a private, access-controlled namespace. Access requires a short-lived signed URL generated by our servers after verifying your authorisation. Documents are never publicly accessible.</p>

      <h2>7. Your Rights</h2>
      <p>Under PIPEDA, you have the right to:</p>
      <ul>
        <li>Access the personal information we hold about you.</li>
        <li>Request correction of inaccurate or incomplete information.</li>
        <li>Withdraw consent, subject to legal or contractual restrictions.</li>
        <li>Lodge a complaint with the Office of the Privacy Commissioner of Canada (OPC) if you believe your privacy rights have been violated.</li>
      </ul>
      <p>To exercise any of these rights, contact us at the address below. We will respond within 30 days.</p>

      <h2>8. Cookies and Tracking</h2>
      <p>The Portal uses a single session cookie (<code>nvp_session</code>) to maintain your authenticated session. This cookie is HttpOnly, Secure, and SameSite=Lax. We do not use advertising cookies, third-party trackers, or analytics cookies beyond standard server-side request logs.</p>

      <h2>9. Data Retention</h2>
      <p>We retain your personal information for as long as your account is active or as needed to fulfil the purposes described in this policy. When you request account deletion, we will remove or anonymise your data within 30 days, except where retention is required by law or legitimate business need (e.g., financial records, audit logs).</p>

      <h2>10. Changes to This Policy</h2>
      <p>We may update this Privacy Policy from time to time. We will notify you of material changes by email or by a notice within the Portal. The effective date at the top of this page reflects when the current version took effect.</p>

      <h2>11. Contact</h2>
      <p>For privacy-related inquiries, requests, or complaints, contact our Privacy Officer:</p>
      <p>Node Ventures Inc.<br />Email: <a href="mailto:admin@nodeventures.ca" target="_blank" rel="noopener noreferrer">admin@nodeventures.ca</a></p>
      <p>You may also view our <a href={href("Terms")}>Terms of Use</a>.</p>
    </window.LegalPage>
  );
}
window.PrivacyPage = PrivacyPage;
